id: P005388
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 11:47:45.449419
source_metadata:
  id: bdr:W1KG6139
  title: གཡུང་དྲུང་བོན་གྱི་མདོ་སྔགས་སེམས་གསུམ་གྱི་གཞུང་།
  author: ''
  volumes:
    cf2084166ff84d03b6e088a324d1bfaf:
      image_group_id: I1KG6206
      title: ''
      volume_number: 1
      total_pages: 508
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
