id: IDF636776
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:21:52+00:00'
last_modified: '2022-06-08T02:43:56.940586+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6139
  title: གཡུང་དྲུང་བོན་གྱི་མདོ་སྔགས་སེམས་གསུམ་གྱི་གཞུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C983:
      image_group_id: I1KG6206
      title: ''
      total_pages: 508
      order: 1
      base_file: C983.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
